<?php // this is an autogenerated file - do not edit (created Wed, 21 Sep 2011 22:13:03 +0900)
spl_autoload_register(
   function($class) {
      static $classes = null;
      if ($classes === null) {
         $classes = array(
            'diggin\\service\\wedata\\client' => '/Service/Wedata/Client.php',
            'diggin\\service\\wedata\\client\\cacheclient' => '/Service/Wedata/Client/CacheClient.php',
            'diggin\\service\\wedata\\client\\mockclient' => '/Service/Wedata/Client/MockClient.php',
            'diggin\\service\\wedata\\client\\serviceclient' => '/Service/Wedata/Client/ServiceClient.php',
            'diggin\\service\\wedata\\database' => '/Service/Wedata/Database.php',
            'diggin\\service\\wedata\\databases' => '/Service/Wedata/Databases.php',
            'diggin\\service\\wedata\\entitygenerator' => '/Service/Wedata/EntityGenerator.php',
            'diggin\\service\\wedata\\exception' => '/Service/Wedata/Exception.php',
            'diggin\\service\\wedata\\filter' => '/Service/Wedata/Filter.php',
            'diggin\\service\\wedata\\item' => '/Service/Wedata/Item.php',
            'diggin\\service\\wedata\\items' => '/Service/Wedata/Items.php',
            'diggin\\service\\wedata\\storage' => '/Service/Wedata/Storage.php',
            'diggin\\service\\wedata\\storage\\adapter' => '/Service/Wedata/Storage/Adapter.php',
            'diggin\\service\\wedata\\storage\\adapter\\sqlite3' => '/Service/Wedata/Storage/Adapter/Sqlite3.php'
          );
      }
      $cn = strtolower($class);
      if (isset($classes[$cn])) {
         require __DIR__ . $classes[$cn];
      }
   }
);
