<?php // this is an autogenerated file - do not edit (created Fri, 23 Sep 2011 01:11:16 +0900)
spl_autoload_register(
   function($class) {
      static $classes = null;
      if ($classes === null) {
         $classes = array(
            'diggin\\service\\wedata\\client' => '/Client.php',
            'diggin\\service\\wedata\\client\\cacheclient' => '/Client/CacheClient.php',
            'diggin\\service\\wedata\\client\\mockclient' => '/Client/MockClient.php',
            'diggin\\service\\wedata\\client\\serviceclient' => '/Client/ServiceClient.php',
            'diggin\\service\\wedata\\database' => '/Database.php',
            'diggin\\service\\wedata\\databases' => '/Databases.php',
            'diggin\\service\\wedata\\entitygenerator' => '/EntityGenerator.php',
            'diggin\\service\\wedata\\exception' => '/Exception.php',
            'diggin\\service\\wedata\\exception\\badfunctioncallexception' => '/Exception/BadFunctionCallException.php',
            'diggin\\service\\wedata\\exception\\badmethodcallexception' => '/Exception/BadMethodCallException.php',
            'diggin\\service\\wedata\\exception\\domainexception' => '/Exception/DomainException.php',
            'diggin\\service\\wedata\\exception\\invalidargumentexception' => '/Exception/InvalidArgumentException.php',
            'diggin\\service\\wedata\\exception\\lengthexception' => '/Exception/LengthException.php',
            'diggin\\service\\wedata\\exception\\logicexception' => '/Exception/LogicException.php',
            'diggin\\service\\wedata\\exception\\outofboundsexception' => '/Exception/OutOfBoundsException.php',
            'diggin\\service\\wedata\\exception\\outofrangeexception' => '/Exception/OutOfRangeException.php',
            'diggin\\service\\wedata\\exception\\overflowexception' => '/Exception/OverflowException.php',
            'diggin\\service\\wedata\\exception\\rangeexception' => '/Exception/RangeException.php',
            'diggin\\service\\wedata\\exception\\runtimeexception' => '/Exception/RuntimeException.php',
            'diggin\\service\\wedata\\exception\\underflowexception' => '/Exception/UnderflowException.php',
            'diggin\\service\\wedata\\exception\\unexpectedvalueexception' => '/Exception/UnexpectedValueException.php',
            'diggin\\service\\wedata\\filter' => '/Filter.php',
            'diggin\\service\\wedata\\item' => '/Item.php',
            'diggin\\service\\wedata\\items' => '/Items.php',
            'diggin\\service\\wedata\\storage' => '/Storage.php',
            'diggin\\service\\wedata\\storage\\adapter' => '/Storage/Adapter.php',
            'diggin\\service\\wedata\\storage\\adapter\\cache' => '/Storage/Adapter/Cache.php',
            'diggin\\service\\wedata\\storage\\adapter\\sqlite3' => '/Storage/Adapter/Sqlite3.php'
          );
      }
      $cn = strtolower($class);
      if (isset($classes[$cn])) {
         require __DIR__ . $classes[$cn];
      }
   }
);
